# Setup
title:               Kemal Gultekin
tagline:             'My personal blog on software, leadership and soft skills.'
description:         'My desc.'
url:                 https://solidpatterns.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kemal GÃ¼ltekin
  url:               https://twitter.com/quemarlos
  email:             gultekin.kemal@gmail.com

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: solidpatterns
repo: SolidPatterns.github.io
branch: main
relative_source: ../
destination: _site/
production_url:  https://solidpatterns.github.io/
source_url:  https://github.com/solidpatterns/SolidPatterns.github.io/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*`